version: '3.8'
services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    command: celery -A workers.tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    working_dir: /app

  # Add your API service here, e.g. FastAPI or Flask
  # api:
  #   build:
  #     context: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #     - celery_worker
  #   volumes:
  #     - .:/app
  #   working_dir: /app
